stages:
  extract_dataset:
    cmd: mkdir -p dataset && cd dataset && unzip ../vk-publics-classification.zip
    deps:
    - vk-publics-classification.zip
    outs:
    - dataset
  prepare_data:
    cmd: mkdir -p generated_data && python prepare_data.py --input dataset/train.csv
      --output generated_data/train.csv
    deps:
    - dataset
    outs:
    - generated_data/train.csv
