stages:
  extract_dataset:
    cmd: mkdir -p dataset && cd dataset && unzip ../vk-publics-classification.zip
    deps:
    - vk-publics-classification.zip
    outs:
    - dataset
  prepare_data:
    cmd: mkdir -p generated_data && python prepare_data.py --input dataset/train.csv
      --output generated_data/train.csv
    deps:
    - dataset
    outs:
    - generated_data/train.csv
  train_val_split:
    cmd: python train_val_split.py --input generated_data/train.csv --output_folder
      generated_data/train_val
    deps:
    - generated_data/train.csv
    params:
    - split.seed
    - split.test_size
    outs:
    - generated_data/train_val
